"""
Database seed data for the pharmacy system.
Contains medication categories, medications, pharmacies, and stock records.
Delete instance/digitalnomads.db before running to force a fresh seed.
"""
from main.models import (
    Organ, Disease, MedicationCategory, Medication, Pharmacy, PharmacyStock
)


CATEGORIES = [
    {"name": "Pain Relief & Anti-inflammatory", "name_ru": "Обезболивающие и противовоспалительные", "name_kz": "Ауырсынуды басатын және қабынуға қарсы", "icon": ""},
    {"name": "Antibiotics", "name_ru": "Антибиотики", "name_kz": "Антибиотиктер", "icon": ""},
    {"name": "Cardiovascular", "name_ru": "Сердечно-сосудистые", "name_kz": "Жүрек-қантамыр", "icon": ""},
    {"name": "Gastrointestinal", "name_ru": "Желудочно-кишечные", "name_kz": "Асқазан-ішек", "icon": ""},
    {"name": "Diabetes & Endocrine", "name_ru": "Диабет и эндокринные", "name_kz": "Диабет және эндокриндік", "icon": ""},
    {"name": "Respiratory", "name_ru": "Дыхательные", "name_kz": "Тыныс алу", "icon": ""},
    {"name": "Vitamins & Supplements", "name_ru": "Витамины и добавки", "name_kz": "Витаминдер мен қоспалар", "icon": ""},
    {"name": "Allergy & Antihistamines", "name_ru": "Аллергия и антигистаминные", "name_kz": "Аллергия және антигистаминдер", "icon": ""},
    {"name": "Nervous System & Sedatives", "name_ru": "Нервная система и седативные", "name_kz": "Жүйке жүйесі және тыныштандырғыштар", "icon": ""},
    {"name": "Antiviral & Immunomodulators", "name_ru": "Противовирусные и иммуномодуляторы", "name_kz": "Вирусқа қарсы және иммуномодуляторлар", "icon": ""},
    {"name": "Hepatoprotectors", "name_ru": "Гепатопротекторы", "name_kz": "Гепатопротекторлар", "icon": ""},
    {"name": "Gynecological & Hormonal", "name_ru": "Гинекологические и гормональные", "name_kz": "Гинекологиялық және гормоналдық", "icon": ""},
    {"name": "ENT & Ophthalmology", "name_ru": "ЛОР и офтальмология", "name_kz": "ЛОР және офтальмология", "icon": ""},
    {"name": "Urology & Herbal", "name_ru": "Урология и растительные", "name_kz": "Урология және өсімдік тектес", "icon": ""},
]

# category index references (1-based after insert)
CAT_PAIN = 0
CAT_ANTIBIOTICS = 1
CAT_CARDIO = 2
CAT_GI = 3
CAT_DIABETES = 4
CAT_RESPIRATORY = 5
CAT_VITAMINS = 6
CAT_ALLERGY = 7
CAT_NERVOUS = 8
CAT_ANTIVIRAL = 9
CAT_HEPATO = 10
CAT_GYNO = 11
CAT_ENT = 12
CAT_UROLOGY = 13

MEDICATIONS = [
    # A
    {
        "name": "Aspirin 500mg",
        "generic_name": "Acetylsalicylic Acid",
        "cat": CAT_PAIN,
        "description": "Pain reliever, fever reducer, and anti-inflammatory. Also used for cardiovascular protection at low doses.",
        "active_ingredient": "Acetylsalicylic Acid 500mg",
        "dosage_forms": "Tablet",
        "available_strengths": "100mg, 325mg, 500mg",
        "manufacturer": "Bayer",
        "side_effects": "Stomach irritation, heartburn, nausea, increased bleeding risk",
        "contraindications": "Peptic ulcer, hemophilia, children under 16 with viral infections",
        "storage_instructions": "Store below 25°C in a dry place",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Amoxicillin 500mg",
        "generic_name": "Amoxicillin",
        "cat": CAT_ANTIBIOTICS,
        "description": "Broad-spectrum penicillin antibiotic for bacterial infections of the respiratory tract, urinary tract, and skin.",
        "active_ingredient": "Amoxicillin trihydrate 500mg",
        "dosage_forms": "Capsule, Suspension",
        "available_strengths": "250mg, 500mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Diarrhea, nausea, skin rash, allergic reactions",
        "contraindications": "Penicillin allergy, infectious mononucleosis",
        "storage_instructions": "Store below 25°C. Reconstituted suspension refrigerate and use within 14 days",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Atorvastatin 20mg",
        "generic_name": "Atorvastatin",
        "cat": CAT_CARDIO,
        "description": "Statin used to lower cholesterol and reduce risk of cardiovascular disease.",
        "active_ingredient": "Atorvastatin Calcium 20mg",
        "dosage_forms": "Tablet",
        "available_strengths": "10mg, 20mg, 40mg, 80mg",
        "manufacturer": "KRKA",
        "side_effects": "Muscle pain, headache, nausea, elevated liver enzymes",
        "contraindications": "Active liver disease, pregnancy, breastfeeding",
        "storage_instructions": "Store below 30°C, protect from moisture",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Almagel Suspension",
        "generic_name": "Aluminium Hydroxide + Magnesium Hydroxide",
        "cat": CAT_GI,
        "description": "Antacid for heartburn, gastritis, and peptic ulcer symptom relief.",
        "active_ingredient": "Aluminium Hydroxide 300mg, Magnesium Hydroxide 100mg per 5ml",
        "dosage_forms": "Suspension",
        "available_strengths": "170ml, 200ml",
        "manufacturer": "Balkanpharma",
        "side_effects": "Constipation, diarrhea, nausea",
        "contraindications": "Severe kidney disease, Alzheimer's disease",
        "storage_instructions": "Store at 15-25°C, do not freeze. Shake before use",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Analgin 500mg",
        "generic_name": "Metamizole Sodium",
        "cat": CAT_PAIN,
        "description": "Analgesic and antipyretic for moderate pain and fever.",
        "active_ingredient": "Metamizole Sodium 500mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "500mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Allergic reactions, low blood pressure, agranulocytosis (rare)",
        "contraindications": "Blood disorders, aspirin-sensitive asthma, pregnancy",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Amlodipine 5mg",
        "generic_name": "Amlodipine",
        "cat": CAT_CARDIO,
        "description": "Calcium channel blocker for high blood pressure and angina.",
        "active_ingredient": "Amlodipine Besylate 5mg",
        "dosage_forms": "Tablet",
        "available_strengths": "2.5mg, 5mg, 10mg",
        "manufacturer": "EGIS",
        "side_effects": "Ankle swelling, dizziness, flushing, headache",
        "contraindications": "Severe aortic stenosis, unstable angina, cardiogenic shock",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Azithromycin 500mg",
        "generic_name": "Azithromycin",
        "cat": CAT_ANTIBIOTICS,
        "description": "Macrolide antibiotic for respiratory, skin, and urogenital infections. Course typically 3-5 days.",
        "active_ingredient": "Azithromycin dihydrate 500mg",
        "dosage_forms": "Tablet, Capsule, Suspension",
        "available_strengths": "250mg, 500mg",
        "manufacturer": "Nobel AFF",
        "side_effects": "Diarrhea, nausea, abdominal pain, headache",
        "contraindications": "Macrolide allergy, severe liver impairment",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # B
    {
        "name": "Bisoprolol 5mg",
        "generic_name": "Bisoprolol",
        "cat": CAT_CARDIO,
        "description": "Beta-blocker for hypertension, heart failure, and angina.",
        "active_ingredient": "Bisoprolol Fumarate 5mg",
        "dosage_forms": "Tablet",
        "available_strengths": "2.5mg, 5mg, 10mg",
        "manufacturer": "Gedeon Richter",
        "side_effects": "Fatigue, dizziness, bradycardia, cold extremities",
        "contraindications": "Severe bradycardia, heart block, uncontrolled heart failure",
        "storage_instructions": "Store below 30°C, protect from moisture",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Bromhexine 8mg",
        "generic_name": "Bromhexine",
        "cat": CAT_RESPIRATORY,
        "description": "Mucolytic agent that thins and loosens mucus in the airways.",
        "active_ingredient": "Bromhexine Hydrochloride 8mg",
        "dosage_forms": "Tablet, Syrup",
        "available_strengths": "4mg, 8mg",
        "manufacturer": "Berlin-Chemie",
        "side_effects": "Nausea, diarrhea, headache",
        "contraindications": "Peptic ulcer, pregnancy first trimester",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Bifidobacterium Probiotic",
        "generic_name": "Bifidobacterium",
        "cat": CAT_GI,
        "description": "Probiotic supplement to restore healthy intestinal microflora after antibiotic use.",
        "active_ingredient": "Bifidobacterium bifidum 10^7 CFU",
        "dosage_forms": "Capsule, Powder",
        "available_strengths": "5 doses",
        "manufacturer": "Vita Biotics",
        "side_effects": "Mild bloating in first days of use",
        "contraindications": "Hypersensitivity to components",
        "storage_instructions": "Store at 2-8°C (refrigerate)",
        "is_otc": True,
        "requires_prescription": False,
    },
    # C
    {
        "name": "Ciprofloxacin 500mg",
        "generic_name": "Ciprofloxacin",
        "cat": CAT_ANTIBIOTICS,
        "description": "Fluoroquinolone antibiotic for urinary, respiratory, and gastrointestinal infections.",
        "active_ingredient": "Ciprofloxacin Hydrochloride 500mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "250mg, 500mg, 750mg",
        "manufacturer": "KRKA",
        "side_effects": "Nausea, diarrhea, dizziness, tendon damage (rare)",
        "contraindications": "Children under 18, pregnancy, epilepsy",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Cetrine 10mg",
        "generic_name": "Cetirizine",
        "cat": CAT_ALLERGY,
        "description": "Second-generation antihistamine for allergic rhinitis, urticaria, and allergic conjunctivitis.",
        "active_ingredient": "Cetirizine Dihydrochloride 10mg",
        "dosage_forms": "Tablet, Syrup",
        "available_strengths": "10mg",
        "manufacturer": "Dr. Reddy's",
        "side_effects": "Drowsiness, dry mouth, fatigue, headache",
        "contraindications": "Severe renal impairment, children under 6",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Ceftriaxone 1g",
        "generic_name": "Ceftriaxone",
        "cat": CAT_ANTIBIOTICS,
        "description": "Third-generation cephalosporin antibiotic for severe bacterial infections. Administered by injection.",
        "active_ingredient": "Ceftriaxone Sodium 1g",
        "dosage_forms": "Powder for Injection",
        "available_strengths": "500mg, 1g, 2g",
        "manufacturer": "Chimpharm",
        "side_effects": "Injection site pain, diarrhea, rash, elevated liver enzymes",
        "contraindications": "Cephalosporin allergy, neonates with jaundice",
        "storage_instructions": "Store below 25°C, protect from light. Use reconstituted solution within 6 hours",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Corvalol Drops",
        "generic_name": "Phenobarbital + Ethyl Bromisovalerate",
        "cat": CAT_NERVOUS,
        "description": "Sedative and antispasmodic drops for nervousness, insomnia, and mild heart complaints.",
        "active_ingredient": "Phenobarbital, Ethyl Bromisovalerate, Peppermint Oil",
        "dosage_forms": "Drops",
        "available_strengths": "25ml, 50ml",
        "manufacturer": "Farmak",
        "side_effects": "Drowsiness, dizziness, slowed reaction time",
        "contraindications": "Severe liver/kidney disease, pregnancy, breastfeeding",
        "storage_instructions": "Store at 15-25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    # D
    {
        "name": "Diclofenac 50mg",
        "generic_name": "Diclofenac",
        "cat": CAT_PAIN,
        "description": "NSAID for pain, inflammation, and swelling in arthritis, injuries, and dental pain.",
        "active_ingredient": "Diclofenac Sodium 50mg",
        "dosage_forms": "Tablet, Gel, Injection",
        "available_strengths": "25mg, 50mg, 75mg, 100mg",
        "manufacturer": "Novartis",
        "side_effects": "Stomach pain, nausea, headache, elevated blood pressure",
        "contraindications": "Active GI bleeding, severe heart failure, third trimester pregnancy",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Drotaverine 40mg (No-shpa)",
        "generic_name": "Drotaverine",
        "cat": CAT_PAIN,
        "description": "Antispasmodic for smooth muscle spasms including abdominal, biliary, and menstrual cramps.",
        "active_ingredient": "Drotaverine Hydrochloride 40mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "40mg, 80mg",
        "manufacturer": "Chinoin (Sanofi)",
        "side_effects": "Dizziness, headache, low blood pressure, nausea",
        "contraindications": "Severe liver/kidney failure, heart failure, children under 6",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Domperidone 10mg",
        "generic_name": "Domperidone",
        "cat": CAT_GI,
        "description": "Antiemetic and prokinetic for nausea, vomiting, and bloating.",
        "active_ingredient": "Domperidone 10mg",
        "dosage_forms": "Tablet, Suspension",
        "available_strengths": "10mg",
        "manufacturer": "Nobel AFF",
        "side_effects": "Dry mouth, headache, rare cardiac arrhythmia",
        "contraindications": "GI bleeding, prolactinoma, severe liver impairment",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # E
    {
        "name": "Enalapril 10mg",
        "generic_name": "Enalapril",
        "cat": CAT_CARDIO,
        "description": "ACE inhibitor for hypertension and heart failure.",
        "active_ingredient": "Enalapril Maleate 10mg",
        "dosage_forms": "Tablet",
        "available_strengths": "5mg, 10mg, 20mg",
        "manufacturer": "EGIS",
        "side_effects": "Dry cough, dizziness, hyperkalemia, headache",
        "contraindications": "History of angioedema, pregnancy, bilateral renal artery stenosis",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Erius 5mg",
        "generic_name": "Desloratadine",
        "cat": CAT_ALLERGY,
        "description": "Non-sedating antihistamine for allergic rhinitis and chronic urticaria.",
        "active_ingredient": "Desloratadine 5mg",
        "dosage_forms": "Tablet, Syrup",
        "available_strengths": "5mg",
        "manufacturer": "Bayer",
        "side_effects": "Headache, dry mouth, fatigue (rare)",
        "contraindications": "Hypersensitivity to desloratadine or loratadine",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Essentiale Forte N",
        "generic_name": "Phospholipids from Soybeans",
        "cat": CAT_GI,
        "description": "Hepatoprotector for liver support and recovery from hepatitis, fatty liver, and toxin damage.",
        "active_ingredient": "Essential Phospholipids 300mg",
        "dosage_forms": "Capsule",
        "available_strengths": "300mg",
        "manufacturer": "Sanofi",
        "side_effects": "Rare: soft stools, stomach discomfort",
        "contraindications": "Hypersensitivity to soya or phospholipids",
        "storage_instructions": "Store below 25°C, do not freeze",
        "is_otc": True,
        "requires_prescription": False,
    },
    # F
    {
        "name": "Furosemide 40mg",
        "generic_name": "Furosemide",
        "cat": CAT_CARDIO,
        "description": "Loop diuretic for edema in heart failure, liver cirrhosis, and kidney disease.",
        "active_ingredient": "Furosemide 40mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "40mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Dehydration, low potassium, dizziness, gout",
        "contraindications": "Anuria, severe hypokalemia, hepatic coma",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Fervex Powder",
        "generic_name": "Paracetamol + Pheniramine + Ascorbic Acid",
        "cat": CAT_RESPIRATORY,
        "description": "Combination powder for cold and flu symptoms including fever, headache, and nasal congestion.",
        "active_ingredient": "Paracetamol 500mg, Pheniramine 25mg, Ascorbic Acid 200mg",
        "dosage_forms": "Powder for Solution",
        "available_strengths": "Single dose sachets",
        "manufacturer": "UPSA (Bristol-Myers Squibb)",
        "side_effects": "Drowsiness, dry mouth, nausea",
        "contraindications": "Severe liver disease, glaucoma, urinary retention",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Fluconazole 150mg",
        "generic_name": "Fluconazole",
        "cat": CAT_ANTIBIOTICS,
        "description": "Antifungal for candidiasis, cryptococcal infections, and fungal prophylaxis.",
        "active_ingredient": "Fluconazole 150mg",
        "dosage_forms": "Capsule, Injection",
        "available_strengths": "50mg, 150mg",
        "manufacturer": "KRKA",
        "side_effects": "Headache, nausea, abdominal pain, rash",
        "contraindications": "Co-administration with terfenadine, QT prolongation",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # G
    {
        "name": "Glucophage 850mg",
        "generic_name": "Metformin",
        "cat": CAT_DIABETES,
        "description": "First-line oral medication for type 2 diabetes. Reduces hepatic glucose production.",
        "active_ingredient": "Metformin Hydrochloride 850mg",
        "dosage_forms": "Tablet",
        "available_strengths": "500mg, 850mg, 1000mg",
        "manufacturer": "Merck",
        "side_effects": "Nausea, diarrhea, metallic taste, vitamin B12 deficiency (long-term)",
        "contraindications": "Severe renal impairment (eGFR <30), diabetic ketoacidosis, lactic acidosis risk",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Glycine 100mg",
        "generic_name": "Glycine",
        "cat": CAT_NERVOUS,
        "description": "Amino acid supplement for reducing mental stress, improving sleep, and supporting brain function.",
        "active_ingredient": "Glycine 100mg",
        "dosage_forms": "Sublingual Tablet",
        "available_strengths": "100mg",
        "manufacturer": "Biotiki",
        "side_effects": "Rare: mild allergic reactions",
        "contraindications": "Hypersensitivity",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # H
    {
        "name": "Heparin Ointment",
        "generic_name": "Heparin Sodium",
        "cat": CAT_CARDIO,
        "description": "Topical anticoagulant for bruises, varicose veins, and superficial thrombophlebitis.",
        "active_ingredient": "Heparin Sodium 1000 IU/g",
        "dosage_forms": "Ointment",
        "available_strengths": "25g, 50g",
        "manufacturer": "Nizhpharm",
        "side_effects": "Skin redness, itching at application site",
        "contraindications": "Open wounds, bleeding disorders, deep vein thrombosis",
        "storage_instructions": "Store at 15-25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # I
    {
        "name": "Ibuprofen 400mg",
        "generic_name": "Ibuprofen",
        "cat": CAT_PAIN,
        "description": "NSAID for pain, fever, and inflammation. Effective for headache, dental pain, and menstrual cramps.",
        "active_ingredient": "Ibuprofen 400mg",
        "dosage_forms": "Tablet, Capsule, Suspension",
        "available_strengths": "200mg, 400mg, 600mg",
        "manufacturer": "Nobel AFF",
        "side_effects": "Stomach upset, heartburn, nausea, dizziness",
        "contraindications": "Active GI ulcer, severe heart failure, third trimester pregnancy",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Imodium 2mg",
        "generic_name": "Loperamide",
        "cat": CAT_GI,
        "description": "Anti-diarrheal agent for acute and chronic diarrhea.",
        "active_ingredient": "Loperamide Hydrochloride 2mg",
        "dosage_forms": "Capsule, Tablet",
        "available_strengths": "2mg",
        "manufacturer": "Johnson & Johnson",
        "side_effects": "Constipation, dizziness, abdominal cramps",
        "contraindications": "Bloody diarrhea, bacterial enterocolitis, children under 6",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Indapamide 2.5mg",
        "generic_name": "Indapamide",
        "cat": CAT_CARDIO,
        "description": "Thiazide-like diuretic for hypertension.",
        "active_ingredient": "Indapamide 2.5mg",
        "dosage_forms": "Tablet",
        "available_strengths": "1.5mg, 2.5mg",
        "manufacturer": "Servier",
        "side_effects": "Headache, dizziness, low potassium, fatigue",
        "contraindications": "Severe renal/hepatic impairment, hypokalemia",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # K
    {
        "name": "Ketonal 100mg",
        "generic_name": "Ketoprofen",
        "cat": CAT_PAIN,
        "description": "NSAID for moderate to severe pain, rheumatic conditions, and post-operative pain.",
        "active_ingredient": "Ketoprofen 100mg",
        "dosage_forms": "Tablet, Capsule, Injection, Gel",
        "available_strengths": "50mg, 100mg, 150mg",
        "manufacturer": "Lek (Sandoz)",
        "side_effects": "Stomach pain, nausea, headache, dizziness",
        "contraindications": "Active GI bleeding, severe heart/kidney/liver failure",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Ketorol 10mg",
        "generic_name": "Ketorolac",
        "cat": CAT_PAIN,
        "description": "Potent NSAID for short-term management of moderate to severe pain.",
        "active_ingredient": "Ketorolac Tromethamine 10mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "10mg",
        "manufacturer": "Dr. Reddy's",
        "side_effects": "GI bleeding, headache, drowsiness, edema",
        "contraindications": "Active peptic ulcer, renal impairment, pregnancy, children under 16",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    # L
    {
        "name": "Losartan 50mg",
        "generic_name": "Losartan",
        "cat": CAT_CARDIO,
        "description": "Angiotensin II receptor blocker (ARB) for hypertension and diabetic nephropathy.",
        "active_ingredient": "Losartan Potassium 50mg",
        "dosage_forms": "Tablet",
        "available_strengths": "25mg, 50mg, 100mg",
        "manufacturer": "KRKA",
        "side_effects": "Dizziness, hyperkalemia, fatigue, upper respiratory infection",
        "contraindications": "Pregnancy, severe hepatic impairment",
        "storage_instructions": "Store below 30°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Linex Capsules",
        "generic_name": "Lactobacillus + Bifidobacterium + Enterococcus",
        "cat": CAT_GI,
        "description": "Probiotic for restoring intestinal microflora after antibiotics or GI disturbances.",
        "active_ingredient": "Lactobacillus acidophilus, Bifidobacterium infantis, Enterococcus faecium",
        "dosage_forms": "Capsule",
        "available_strengths": "16 capsules, 32 capsules",
        "manufacturer": "Lek (Sandoz)",
        "side_effects": "Rare: mild bloating",
        "contraindications": "Hypersensitivity to components",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Lizobact Tablets",
        "generic_name": "Lysozyme + Pyridoxine",
        "cat": CAT_RESPIRATORY,
        "description": "Antiseptic lozenges for sore throat, stomatitis, and oral mucosa infections.",
        "active_ingredient": "Lysozyme Hydrochloride 20mg, Pyridoxine HCl 10mg",
        "dosage_forms": "Lozenge",
        "available_strengths": "20mg + 10mg",
        "manufacturer": "Bosnalijek",
        "side_effects": "Rare: allergic reactions",
        "contraindications": "Children under 3, lactose intolerance",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Loratadine 10mg",
        "generic_name": "Loratadine",
        "cat": CAT_ALLERGY,
        "description": "Non-sedating antihistamine for seasonal allergies, hay fever, and allergic skin reactions.",
        "active_ingredient": "Loratadine 10mg",
        "dosage_forms": "Tablet, Syrup",
        "available_strengths": "10mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Headache, drowsiness (rare), dry mouth",
        "contraindications": "Severe hepatic impairment, children under 2",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # M
    {
        "name": "Mezim Forte",
        "generic_name": "Pancreatin",
        "cat": CAT_GI,
        "description": "Digestive enzyme supplement for indigestion, bloating, and pancreatic insufficiency.",
        "active_ingredient": "Pancreatin (Lipase 3500 FIP, Amylase 4200 FIP, Protease 250 FIP)",
        "dosage_forms": "Tablet",
        "available_strengths": "Forte, Forte 10000",
        "manufacturer": "Berlin-Chemie",
        "side_effects": "Nausea, diarrhea, allergic reactions (rare)",
        "contraindications": "Acute pancreatitis, pork protein allergy",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Metformin 1000mg",
        "generic_name": "Metformin",
        "cat": CAT_DIABETES,
        "description": "Oral antidiabetic for type 2 diabetes management.",
        "active_ingredient": "Metformin Hydrochloride 1000mg",
        "dosage_forms": "Tablet",
        "available_strengths": "500mg, 850mg, 1000mg",
        "manufacturer": "Chimpharm",
        "side_effects": "GI upset, metallic taste, lactic acidosis (very rare)",
        "contraindications": "Renal impairment (eGFR <30), acute metabolic acidosis",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Mukaltin Tablets",
        "generic_name": "Althaea Root Extract",
        "cat": CAT_RESPIRATORY,
        "description": "Herbal expectorant for productive cough in bronchitis, tracheitis, and pneumonia.",
        "active_ingredient": "Althaea medicinal herb extract 50mg",
        "dosage_forms": "Tablet",
        "available_strengths": "50mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Rare: nausea, allergic reactions",
        "contraindications": "Peptic ulcer, hypersensitivity",
        "storage_instructions": "Store below 25°C in a dry place",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Mildronat 500mg",
        "generic_name": "Meldonium",
        "cat": CAT_CARDIO,
        "description": "Cardioprotective agent for ischemic heart disease, heart failure, and physical overexertion.",
        "active_ingredient": "Meldonium 500mg",
        "dosage_forms": "Capsule, Injection",
        "available_strengths": "250mg, 500mg",
        "manufacturer": "Grindex",
        "side_effects": "Tachycardia, dyspepsia, agitation",
        "contraindications": "Increased intracranial pressure, pregnancy, children under 18",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # N
    {
        "name": "Nurofen 200mg",
        "generic_name": "Ibuprofen",
        "cat": CAT_PAIN,
        "description": "Branded ibuprofen for headache, muscle pain, fever, and menstrual pain.",
        "active_ingredient": "Ibuprofen 200mg",
        "dosage_forms": "Tablet, Capsule",
        "available_strengths": "200mg, 400mg",
        "manufacturer": "Reckitt Benckiser",
        "side_effects": "Stomach irritation, heartburn, headache",
        "contraindications": "Active GI ulceration, aspirin-sensitive asthma",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Nimesil 100mg",
        "generic_name": "Nimesulide",
        "cat": CAT_PAIN,
        "description": "NSAID for acute pain, dental pain, and dysmenorrhoea. Taken as granules dissolved in water.",
        "active_ingredient": "Nimesulide 100mg",
        "dosage_forms": "Granules for Suspension",
        "available_strengths": "100mg sachets",
        "manufacturer": "Menarini",
        "side_effects": "Nausea, diarrhea, elevated liver enzymes, dizziness",
        "contraindications": "Hepatotoxicity history, active GI bleeding, children under 12",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Noshpa Forte 80mg",
        "generic_name": "Drotaverine",
        "cat": CAT_PAIN,
        "description": "Strong antispasmodic for biliary and renal colic, and severe menstrual cramps.",
        "active_ingredient": "Drotaverine Hydrochloride 80mg",
        "dosage_forms": "Tablet",
        "available_strengths": "80mg",
        "manufacturer": "Chinoin (Sanofi)",
        "side_effects": "Headache, dizziness, low blood pressure",
        "contraindications": "Severe hepatic/renal failure, low cardiac output",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    # O
    {
        "name": "Omeprazole 20mg",
        "generic_name": "Omeprazole",
        "cat": CAT_GI,
        "description": "Proton pump inhibitor for GERD, peptic ulcer, and H. pylori eradication therapy.",
        "active_ingredient": "Omeprazole 20mg",
        "dosage_forms": "Capsule",
        "available_strengths": "20mg, 40mg",
        "manufacturer": "KRKA",
        "side_effects": "Headache, diarrhea, nausea, vitamin B12 deficiency (long-term)",
        "contraindications": "Hypersensitivity, co-administration with nelfinavir",
        "storage_instructions": "Store below 25°C, protect from moisture",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Otrivin Nasal Spray",
        "generic_name": "Xylometazoline",
        "cat": CAT_RESPIRATORY,
        "description": "Nasal decongestant for relief of nasal congestion due to cold or allergies.",
        "active_ingredient": "Xylometazoline Hydrochloride 0.1%",
        "dosage_forms": "Nasal Spray",
        "available_strengths": "0.05%, 0.1%",
        "manufacturer": "Novartis",
        "side_effects": "Nasal dryness, burning sensation, rebound congestion with prolonged use",
        "contraindications": "Atrophic rhinitis, recent nasal surgery, MAO inhibitors",
        "storage_instructions": "Store below 25°C, do not freeze",
        "is_otc": True,
        "requires_prescription": False,
    },
    # P
    {
        "name": "Paracetamol 500mg",
        "generic_name": "Acetaminophen",
        "cat": CAT_PAIN,
        "description": "Analgesic and antipyretic for mild to moderate pain and fever.",
        "active_ingredient": "Paracetamol 500mg",
        "dosage_forms": "Tablet, Syrup, Suppository",
        "available_strengths": "125mg, 250mg, 500mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Rare at recommended doses. Liver damage with overdose",
        "contraindications": "Severe hepatic impairment, alcohol dependence",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Panangin Tablets",
        "generic_name": "Potassium Aspartate + Magnesium Aspartate",
        "cat": CAT_CARDIO,
        "description": "Potassium and magnesium supplement for cardiac arrhythmias and electrolyte imbalance.",
        "active_ingredient": "Potassium Aspartate 158mg, Magnesium Aspartate 140mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "Standard dose",
        "manufacturer": "Gedeon Richter",
        "side_effects": "Nausea, diarrhea, hyperkalemia (with high doses)",
        "contraindications": "Hyperkalemia, hypermagnesemia, severe renal impairment, Addison's disease",
        "storage_instructions": "Store at 15-30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Pantoprazole 40mg",
        "generic_name": "Pantoprazole",
        "cat": CAT_GI,
        "description": "Proton pump inhibitor for GERD, erosive esophagitis, and Zollinger-Ellison syndrome.",
        "active_ingredient": "Pantoprazole Sodium 40mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "20mg, 40mg",
        "manufacturer": "KRKA",
        "side_effects": "Headache, diarrhea, flatulence, joint pain",
        "contraindications": "Hypersensitivity to benzimidazoles",
        "storage_instructions": "Store below 25°C, protect from moisture",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Pregabalin 75mg",
        "generic_name": "Pregabalin",
        "cat": CAT_NERVOUS,
        "description": "Anticonvulsant for neuropathic pain, epilepsy, and generalized anxiety disorder.",
        "active_ingredient": "Pregabalin 75mg",
        "dosage_forms": "Capsule",
        "available_strengths": "25mg, 50mg, 75mg, 150mg, 300mg",
        "manufacturer": "Pfizer",
        "side_effects": "Dizziness, drowsiness, weight gain, blurred vision",
        "contraindications": "Hypersensitivity, galactose intolerance",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # R
    {
        "name": "Rennie Tablets",
        "generic_name": "Calcium Carbonate + Magnesium Carbonate",
        "cat": CAT_GI,
        "description": "Fast-acting antacid for heartburn, indigestion, and acid reflux.",
        "active_ingredient": "Calcium Carbonate 680mg, Magnesium Carbonate 80mg",
        "dosage_forms": "Chewable Tablet",
        "available_strengths": "Standard dose",
        "manufacturer": "Bayer",
        "side_effects": "Rare: constipation, diarrhea",
        "contraindications": "Hypercalcemia, severe renal failure, nephrolithiasis",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Riboxin 200mg",
        "generic_name": "Inosine",
        "cat": CAT_CARDIO,
        "description": "Metabolic agent for myocardial ischemia, arrhythmias, and liver protection.",
        "active_ingredient": "Inosine 200mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "200mg",
        "manufacturer": "Darnitsa",
        "side_effects": "Allergic reactions, gout exacerbation, itching",
        "contraindications": "Gout, hyperuricemia, renal failure",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    # S
    {
        "name": "Smecta Powder",
        "generic_name": "Diosmectite",
        "cat": CAT_GI,
        "description": "Adsorbent for acute and chronic diarrhea, heartburn, and GI discomfort.",
        "active_ingredient": "Diosmectite 3g",
        "dosage_forms": "Powder for Suspension",
        "available_strengths": "3g sachets",
        "manufacturer": "Ipsen",
        "side_effects": "Constipation (rare), bloating",
        "contraindications": "Intestinal obstruction, fructose intolerance",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Suprastin 25mg",
        "generic_name": "Chloropyramine",
        "cat": CAT_ALLERGY,
        "description": "First-generation antihistamine for allergic reactions, urticaria, and angioedema.",
        "active_ingredient": "Chloropyramine Hydrochloride 25mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "25mg",
        "manufacturer": "EGIS",
        "side_effects": "Drowsiness, dry mouth, dizziness, urinary retention",
        "contraindications": "Acute asthma attack, newborns, pregnancy, glaucoma",
        "storage_instructions": "Store at 15-25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Sumamed 500mg",
        "generic_name": "Azithromycin",
        "cat": CAT_ANTIBIOTICS,
        "description": "Branded azithromycin for respiratory, ENT, skin, and urogenital infections.",
        "active_ingredient": "Azithromycin Dihydrate 500mg",
        "dosage_forms": "Tablet, Capsule",
        "available_strengths": "125mg, 250mg, 500mg",
        "manufacturer": "Pliva (Teva)",
        "side_effects": "Diarrhea, nausea, abdominal pain",
        "contraindications": "Macrolide allergy, severe hepatic impairment",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # T
    {
        "name": "Tempalgin Tablets",
        "generic_name": "Metamizole + Triacetonamine",
        "cat": CAT_PAIN,
        "description": "Analgesic-antipyretic with mild sedative effect for headache, toothache, and neuralgia.",
        "active_ingredient": "Metamizole Sodium 500mg, Triacetonamine 20mg",
        "dosage_forms": "Tablet",
        "available_strengths": "Standard dose",
        "manufacturer": "Sopharma",
        "side_effects": "Drowsiness, dizziness, hypotension",
        "contraindications": "Blood disorders, severe liver/kidney disease, pregnancy",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Terzhinan Vaginal Tablets",
        "generic_name": "Ternidazole + Neomycin + Nystatin + Prednisolone",
        "cat": CAT_ANTIBIOTICS,
        "description": "Combined vaginal tablets for bacterial vaginosis, candidiasis, and mixed infections.",
        "active_ingredient": "Ternidazole 200mg, Neomycin 100mg, Nystatin 100000 IU, Prednisolone 3mg",
        "dosage_forms": "Vaginal Tablet",
        "available_strengths": "6 tablets, 10 tablets",
        "manufacturer": "Laboratoires Bouchara-Recordati",
        "side_effects": "Local burning, itching (initial)",
        "contraindications": "Hypersensitivity to components, first trimester pregnancy",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # U
    {
        "name": "Ursosan 250mg",
        "generic_name": "Ursodeoxycholic Acid",
        "cat": CAT_GI,
        "description": "Hepatoprotector for gallstones, biliary sludge, and chronic liver diseases.",
        "active_ingredient": "Ursodeoxycholic Acid 250mg",
        "dosage_forms": "Capsule",
        "available_strengths": "250mg, 500mg",
        "manufacturer": "PRO.MED.CS Praha",
        "side_effects": "Diarrhea, nausea, calcification of gallstones (rare)",
        "contraindications": "Calcified gallstones, acute cholecystitis, bile duct obstruction",
        "storage_instructions": "Store below 25°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    # V
    {
        "name": "Validol Tablets",
        "generic_name": "Menthol in Menthyl Isovalerate",
        "cat": CAT_NERVOUS,
        "description": "Mild sedative and coronary vasodilator for anxiety, nervous heart palpitations, and motion sickness.",
        "active_ingredient": "Menthol solution in Menthyl Isovalerate 60mg",
        "dosage_forms": "Sublingual Tablet, Drops",
        "available_strengths": "60mg",
        "manufacturer": "Darnitsa",
        "side_effects": "Rare: nausea, watery eyes",
        "contraindications": "Hypersensitivity, severe hypotension",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Vitamin C 500mg",
        "generic_name": "Ascorbic Acid",
        "cat": CAT_VITAMINS,
        "description": "Vitamin supplement for immune support, antioxidant protection, and iron absorption.",
        "active_ingredient": "Ascorbic Acid 500mg",
        "dosage_forms": "Tablet, Effervescent Tablet",
        "available_strengths": "250mg, 500mg, 1000mg",
        "manufacturer": "Various",
        "side_effects": "GI upset at high doses, kidney stones (rare, very high doses)",
        "contraindications": "Hyperoxaluria, severe renal impairment",
        "storage_instructions": "Store below 25°C, protect from moisture",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Vitamin D3 1000 IU",
        "generic_name": "Cholecalciferol",
        "cat": CAT_VITAMINS,
        "description": "Vitamin D supplement for bone health, calcium absorption, and immune function.",
        "active_ingredient": "Cholecalciferol 1000 IU (25mcg)",
        "dosage_forms": "Capsule, Drops",
        "available_strengths": "400 IU, 1000 IU, 2000 IU, 5000 IU",
        "manufacturer": "Solgar",
        "side_effects": "Rare at recommended doses: nausea, hypercalcemia (with excess)",
        "contraindications": "Hypercalcemia, hypervitaminosis D, severe renal impairment",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Verapamil 80mg",
        "generic_name": "Verapamil",
        "cat": CAT_CARDIO,
        "description": "Calcium channel blocker for hypertension, angina, and supraventricular arrhythmias.",
        "active_ingredient": "Verapamil Hydrochloride 80mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "40mg, 80mg, 120mg, 240mg",
        "manufacturer": "EGIS",
        "side_effects": "Constipation, dizziness, headache, bradycardia",
        "contraindications": "Severe heart failure, AV block, sick sinus syndrome, beta-blocker co-administration",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    # W
    {
        "name": "Warfarin 2.5mg",
        "generic_name": "Warfarin",
        "cat": CAT_CARDIO,
        "description": "Oral anticoagulant for prevention and treatment of blood clots, DVT, and pulmonary embolism.",
        "active_ingredient": "Warfarin Sodium 2.5mg",
        "dosage_forms": "Tablet",
        "available_strengths": "1mg, 2.5mg, 5mg",
        "manufacturer": "Nycomed (Takeda)",
        "side_effects": "Bleeding, bruising, hair loss, nausea",
        "contraindications": "Active bleeding, pregnancy, severe hypertension, recent surgery",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    # X
    {
        "name": "Xylometazoline Nasal Drops 0.1%",
        "generic_name": "Xylometazoline",
        "cat": CAT_RESPIRATORY,
        "description": "Nasal decongestant drops for nasal congestion in colds, sinusitis, and allergies.",
        "active_ingredient": "Xylometazoline Hydrochloride 0.1%",
        "dosage_forms": "Nasal Drops",
        "available_strengths": "0.05%, 0.1%",
        "manufacturer": "Chimpharm",
        "side_effects": "Nasal dryness, sneezing, rebound congestion with prolonged use",
        "contraindications": "Atrophic rhinitis, glaucoma, MAO inhibitor use",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # Y
    {
        "name": "Yodomarin 200mcg",
        "generic_name": "Potassium Iodide",
        "cat": CAT_VITAMINS,
        "description": "Iodine supplement for prevention and treatment of iodine deficiency and thyroid support.",
        "active_ingredient": "Potassium Iodide 200mcg",
        "dosage_forms": "Tablet",
        "available_strengths": "100mcg, 200mcg",
        "manufacturer": "Berlin-Chemie",
        "side_effects": "Rare: skin rash, thyroid dysfunction (with excessive intake)",
        "contraindications": "Hyperthyroidism, dermatitis herpetiformis, thyroid autonomy",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    # Z
    {
        "name": "Zodak 10mg",
        "generic_name": "Cetirizine",
        "cat": CAT_ALLERGY,
        "description": "Non-sedating antihistamine for seasonal and perennial allergic rhinitis and urticaria.",
        "active_ingredient": "Cetirizine Dihydrochloride 10mg",
        "dosage_forms": "Tablet, Drops",
        "available_strengths": "10mg",
        "manufacturer": "Zentiva",
        "side_effects": "Drowsiness, dry mouth, headache",
        "contraindications": "Severe renal impairment, children under 6 (tablets)",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    # Additional medications for more coverage
    {
        "name": "Lisinopril 10mg",
        "generic_name": "Lisinopril",
        "cat": CAT_CARDIO,
        "description": "ACE inhibitor for hypertension and heart failure. Reduces risk of cardiovascular events.",
        "active_ingredient": "Lisinopril 10mg",
        "dosage_forms": "Tablet",
        "available_strengths": "5mg, 10mg, 20mg",
        "manufacturer": "EGIS",
        "side_effects": "Dry cough, dizziness, headache, hyperkalemia",
        "contraindications": "Angioedema history, pregnancy, bilateral renal artery stenosis",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Loperamide 2mg",
        "generic_name": "Loperamide",
        "cat": CAT_GI,
        "description": "Generic anti-diarrheal agent for symptomatic treatment of acute diarrhea.",
        "active_ingredient": "Loperamide Hydrochloride 2mg",
        "dosage_forms": "Capsule",
        "available_strengths": "2mg",
        "manufacturer": "Chimpharm",
        "side_effects": "Constipation, abdominal cramps, dizziness",
        "contraindications": "Bloody diarrhea, bacterial enterocolitis",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Magnesium B6 Forte",
        "generic_name": "Magnesium + Pyridoxine",
        "cat": CAT_VITAMINS,
        "description": "Magnesium and vitamin B6 supplement for muscle cramps, fatigue, and stress.",
        "active_ingredient": "Magnesium Lactate 470mg, Pyridoxine HCl 5mg",
        "dosage_forms": "Tablet, Solution",
        "available_strengths": "Standard dose",
        "manufacturer": "Sanofi",
        "side_effects": "Diarrhea (at high doses), stomach discomfort",
        "contraindications": "Severe renal failure, phenylketonuria (solution)",
        "storage_instructions": "Store below 30°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Omega-3 Fish Oil 1000mg",
        "generic_name": "Omega-3 Fatty Acids (EPA + DHA)",
        "cat": CAT_VITAMINS,
        "description": "Dietary supplement for cardiovascular health, brain function, and anti-inflammatory support.",
        "active_ingredient": "Fish Oil 1000mg (EPA 180mg, DHA 120mg)",
        "dosage_forms": "Soft Capsule",
        "available_strengths": "500mg, 1000mg",
        "manufacturer": "Solgar",
        "side_effects": "Fishy aftertaste, burping, mild GI upset",
        "contraindications": "Fish allergy, active bleeding disorders",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Dexamethasone 0.5mg",
        "generic_name": "Dexamethasone",
        "cat": CAT_ALLERGY,
        "description": "Corticosteroid for severe allergic reactions, inflammation, and autoimmune conditions.",
        "active_ingredient": "Dexamethasone 0.5mg",
        "dosage_forms": "Tablet, Injection",
        "available_strengths": "0.5mg, 4mg",
        "manufacturer": "KRKA",
        "side_effects": "Weight gain, elevated blood sugar, mood changes, osteoporosis (long-term)",
        "contraindications": "Systemic fungal infections, live vaccines during high-dose therapy",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Salbutamol Inhaler 100mcg",
        "generic_name": "Salbutamol",
        "cat": CAT_RESPIRATORY,
        "description": "Bronchodilator inhaler for asthma and COPD symptom relief.",
        "active_ingredient": "Salbutamol Sulfate 100mcg/dose",
        "dosage_forms": "Metered-Dose Inhaler",
        "available_strengths": "100mcg/dose (200 doses)",
        "manufacturer": "GlaxoSmithKline",
        "side_effects": "Tremor, headache, tachycardia, restlessness",
        "contraindications": "Hypersensitivity to salbutamol",
        "storage_instructions": "Store below 30°C, do not freeze, protect from sunlight",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Insulin Glargine (Lantus)",
        "generic_name": "Insulin Glargine",
        "cat": CAT_DIABETES,
        "description": "Long-acting insulin analog for type 1 and type 2 diabetes management.",
        "active_ingredient": "Insulin Glargine 100 IU/ml",
        "dosage_forms": "Injection (SoloSTAR pen)",
        "available_strengths": "100 IU/ml, 300 IU/ml",
        "manufacturer": "Sanofi",
        "side_effects": "Hypoglycemia, injection site reactions, weight gain",
        "contraindications": "Hypoglycemia, hypersensitivity to insulin glargine",
        "storage_instructions": "Store unopened at 2-8°C. In use: store below 30°C for up to 28 days",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Gliclazide 60mg MR",
        "generic_name": "Gliclazide",
        "cat": CAT_DIABETES,
        "description": "Sulfonylurea for type 2 diabetes when diet and exercise are insufficient.",
        "active_ingredient": "Gliclazide 60mg Modified Release",
        "dosage_forms": "Tablet (MR)",
        "available_strengths": "30mg, 60mg",
        "manufacturer": "Servier",
        "side_effects": "Hypoglycemia, weight gain, GI disturbances",
        "contraindications": "Type 1 diabetes, diabetic ketoacidosis, severe liver/kidney disease",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "ACC 200mg",
        "generic_name": "Acetylcysteine",
        "cat": CAT_RESPIRATORY,
        "description": "Mucolytic for productive cough in bronchitis, pneumonia, and cystic fibrosis.",
        "active_ingredient": "Acetylcysteine 200mg",
        "dosage_forms": "Effervescent Tablet, Granules",
        "available_strengths": "100mg, 200mg, 600mg",
        "manufacturer": "Sandoz",
        "side_effects": "Nausea, vomiting, diarrhea, rash",
        "contraindications": "Peptic ulcer, pulmonary hemorrhage, children under 2",
        "storage_instructions": "Store below 25°C, protect from moisture",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Berodual Inhalation Solution",
        "generic_name": "Ipratropium + Fenoterol",
        "cat": CAT_RESPIRATORY,
        "description": "Combined bronchodilator solution for nebulizer use in asthma and COPD.",
        "active_ingredient": "Ipratropium Bromide 0.25mg + Fenoterol HBr 0.5mg per ml",
        "dosage_forms": "Inhalation Solution",
        "available_strengths": "20ml bottle",
        "manufacturer": "Boehringer Ingelheim",
        "side_effects": "Dry mouth, headache, tremor, cough",
        "contraindications": "Hypertrophic cardiomyopathy, tachyarrhythmia",
        "storage_instructions": "Store below 30°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Tantum Verde Spray",
        "generic_name": "Benzydamine",
        "cat": CAT_RESPIRATORY,
        "description": "Anti-inflammatory throat spray for pharyngitis, tonsillitis, and oral mucosa inflammation.",
        "active_ingredient": "Benzydamine Hydrochloride 0.15%",
        "dosage_forms": "Spray, Solution, Lozenges",
        "available_strengths": "30ml spray",
        "manufacturer": "Angelini",
        "side_effects": "Numbness, burning sensation in mouth (transient)",
        "contraindications": "Children under 6 (spray), phenylketonuria (lozenges)",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Nifedipine 10mg",
        "generic_name": "Nifedipine",
        "cat": CAT_CARDIO,
        "description": "Calcium channel blocker for hypertension and angina pectoris.",
        "active_ingredient": "Nifedipine 10mg",
        "dosage_forms": "Tablet, Capsule",
        "available_strengths": "10mg, 20mg, 30mg, 60mg",
        "manufacturer": "Bayer",
        "side_effects": "Flushing, headache, dizziness, ankle edema, tachycardia",
        "contraindications": "Cardiogenic shock, advanced aortic stenosis, acute MI",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Clotrimazole Cream 1%",
        "generic_name": "Clotrimazole",
        "cat": CAT_ANTIBIOTICS,
        "description": "Topical antifungal for skin and vaginal fungal infections, including athlete's foot and candidiasis.",
        "active_ingredient": "Clotrimazole 1%",
        "dosage_forms": "Cream, Vaginal Tablet",
        "available_strengths": "1% (20g, 30g)",
        "manufacturer": "Bayer",
        "side_effects": "Local irritation, burning, redness",
        "contraindications": "Hypersensitivity to clotrimazole",
        "storage_instructions": "Store below 25°C",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Calcium D3 Nycomed",
        "generic_name": "Calcium Carbonate + Cholecalciferol",
        "cat": CAT_VITAMINS,
        "description": "Calcium and vitamin D3 supplement for bone health, osteoporosis prevention.",
        "active_ingredient": "Calcium Carbonate 1250mg (500mg Ca), Cholecalciferol 200 IU",
        "dosage_forms": "Chewable Tablet",
        "available_strengths": "Standard, Forte (500mg Ca + 400 IU D3)",
        "manufacturer": "Takeda",
        "side_effects": "Constipation, flatulence, nausea",
        "contraindications": "Hypercalcemia, hypervitaminosis D, severe renal failure",
        "storage_instructions": "Store below 25°C, keep container tightly closed",
        "is_otc": True,
        "requires_prescription": False,
    },
    {
        "name": "Janit (Dapagliflozin) 10mg",
        "generic_name": "Dapagliflozin",
        "cat": CAT_DIABETES,
        "description": "SGLT2 inhibitor for type 2 diabetes and heart failure. Promotes glucose excretion through urine.",
        "active_ingredient": "Dapagliflozin 10mg",
        "dosage_forms": "Tablet",
        "available_strengths": "5mg, 10mg",
        "manufacturer": "AstraZeneca",
        "side_effects": "Urinary tract infections, genital fungal infections, polyuria, hypotension",
        "contraindications": "Type 1 diabetes, dialysis, severe renal impairment (eGFR <25)",
        "storage_instructions": "Store below 30°C",
        "is_otc": False,
        "requires_prescription": True,
    },
    {
        "name": "Qudesan (Coenzyme Q10) 30mg",
        "generic_name": "Ubiquinone (Coenzyme Q10)",
        "cat": CAT_VITAMINS,
        "description": "Antioxidant supplement for energy metabolism, heart support, and anti-aging.",
        "active_ingredient": "Ubiquinone (CoQ10) 30mg",
        "dosage_forms": "Drops, Tablet",
        "available_strengths": "30mg, 60mg",
        "manufacturer": "Vneshtorg Pharma",
        "side_effects": "Rare: mild GI upset, insomnia",
        "contraindications": "Hypersensitivity, children under 1 year",
        "storage_instructions": "Store below 25°C, protect from light",
        "is_otc": True,
        "requires_prescription": False,
    },
]

PHARMACIES = [
    {
        "name": "Euroaptieka",
        "name_ru": "Евроаптека",
        "name_kz": "Еуроаптека",
        "address": "ul. Abaya 150, Almaty",
        "phone": "+7-727-250-0100",
        "city": "Almaty",
        "city_ru": "Алматы",
        "city_kz": "Алматы",
        "country": "Kazakhstan",
        "operates_24_7": True,
        "delivery_available": True,
    },
    {
        "name": "Sadykhan Apteka",
        "name_ru": "Садыхан Аптека",
        "name_kz": "Садықхан Аптека",
        "address": "pr. Dostyk 89, Almaty",
        "phone": "+7-727-250-0200",
        "city": "Almaty",
        "city_ru": "Алматы",
        "city_kz": "Алматы",
        "country": "Kazakhstan",
        "operates_24_7": False,
    },
    {
        "name": "Apteka Plus",
        "name_ru": "Аптека Плюс",
        "name_kz": "Аптека Плюс",
        "address": "pr. Respubliki 44, Astana",
        "phone": "+7-717-225-0100",
        "city": "Astana",
        "city_ru": "Астана",
        "city_kz": "Астана",
        "country": "Kazakhstan",
        "operates_24_7": True,
        "delivery_available": True,
    },
    {
        "name": "Biosphera Apteka",
        "name_ru": "Биосфера Аптека",
        "name_kz": "Биосфера Аптека",
        "address": "ul. Kenesary 65, Astana",
        "phone": "+7-717-225-0200",
        "city": "Astana",
        "city_ru": "Астана",
        "city_kz": "Астана",
        "country": "Kazakhstan",
        "operates_24_7": False,
    },
    {
        "name": "Pharma Group",
        "name_ru": "Фарма Групп",
        "name_kz": "Фарма Групп",
        "address": "ul. Tauke Khan 12, Shymkent",
        "phone": "+7-725-260-0100",
        "city": "Shymkent",
        "city_ru": "Шымкент",
        "city_kz": "Шымкент",
        "country": "Kazakhstan",
        "operates_24_7": False,
    },
    {
        "name": "Deta Pharm",
        "name_ru": "Дета Фарм",
        "name_kz": "Дета Фарм",
        "address": "pr. Bukhar-Zhyrau 35, Karaganda",
        "phone": "+7-721-242-0100",
        "city": "Karaganda",
        "city_ru": "Караганда",
        "city_kz": "Қарағанды",
        "country": "Kazakhstan",
        "operates_24_7": False,
    },
    {
        "name": "Gippokrat Apteka",
        "name_ru": "Гиппократ Аптека",
        "name_kz": "Гиппократ Аптека",
        "address": "pr. Abilkayyr khan 67, Aktobe",
        "phone": "+7-713-254-0100",
        "city": "Aktobe",
        "city_ru": "Актобе",
        "city_kz": "Ақтөбе",
        "country": "Kazakhstan",
        "operates_24_7": False,
        "delivery_available": True,
    },
    {
        "name": "Global Pharm",
        "name_ru": "Глобал Фарм",
        "name_kz": "Глобал Фарм",
        "address": "ul. Satpayev 22, Atyrau",
        "phone": "+7-712-232-0100",
        "city": "Atyrau",
        "city_ru": "Атырау",
        "city_kz": "Атырау",
        "country": "Kazakhstan",
        "operates_24_7": False,
    },
]


def seed_database(db):
    """Seed all pharmacy data. Idempotent - skips if data already exists."""
    from main.models import Organ, Disease

    # Seed organs/diseases
    if Organ.query.count() == 0:
        h = Organ(name='Heart', system='Cardiovascular', description='The heart pumps blood throughout the body.')
        l = Organ(name='Liver', system='Digestive', description='The liver detoxifies chemicals and metabolizes drugs.')
        lu = Organ(name='Lungs', system='Respiratory', description='The lungs help in breathing and oxygen exchange.')
        db.session.add_all([h, l, lu])
        db.session.commit()

        db.session.add_all([
            Disease(name='Myocardial Infarction', symptoms='Chest pain, shortness of breath', organ_id=h.id),
            Disease(name='Cirrhosis', symptoms='Fatigue, swelling, jaundice', organ_id=l.id),
            Disease(name='Asthma', symptoms='Wheezing, coughing', organ_id=lu.id),
        ])
        db.session.commit()

    # Seed categories
    if MedicationCategory.query.count() == 0:
        cat_objects = []
        for cat_data in CATEGORIES:
            cat_objects.append(MedicationCategory(**cat_data))
        db.session.add_all(cat_objects)
        db.session.commit()

    # Seed medications
    if Medication.query.count() == 0:
        categories = MedicationCategory.query.all()

        med_objects = []
        for med_data in MEDICATIONS:
            cat_idx = med_data.pop("cat")
            med_data["category_id"] = categories[cat_idx].id
            med_objects.append(Medication(**med_data))

        db.session.add_all(med_objects)
        db.session.commit()

    # Seed pharmacies
    if Pharmacy.query.count() == 0:
        pharm_objects = []
        for pharm_data in PHARMACIES:
            pharm_objects.append(Pharmacy(**pharm_data))
        db.session.add_all(pharm_objects)
        db.session.commit()

    # Seed pharmacy stocks for ALL medications
    if PharmacyStock.query.count() == 0:
        medications = Medication.query.all()
        pharmacies = Pharmacy.query.all()
        num_pharmacies = len(pharmacies)

        stocks = []
        for i, med in enumerate(medications):
            # Each medication appears in 3-6 pharmacies (deterministic based on index)
            num_stores = 3 + (i % 4)  # 3, 4, 5, or 6
            start_idx = i % num_pharmacies

            # Price range: OTC 300-3000 KZT, Rx 800-15000 KZT
            if med.is_otc:
                base_price = 500 + (i * 137) % 2500
            else:
                base_price = 1200 + (i * 211) % 12000

            for j in range(num_stores):
                pharm_idx = (start_idx + j) % num_pharmacies
                pharmacy = pharmacies[pharm_idx]
                # Vary price slightly per pharmacy
                price = base_price + (j * 50) - 100
                if price < 200:
                    price = 200
                quantity = 10 + (i * 7 + j * 13) % 190

                stocks.append(PharmacyStock(
                    pharmacy_id=pharmacy.id,
                    medication_id=med.id,
                    quantity=quantity,
                    price=float(price),
                    currency='KZT',
                ))

        db.session.add_all(stocks)
        db.session.commit()
